config/routes.rb
Todo::Application.routes.draw do
  resources :histories

  match '/auth/:provider/callback' => 'authentications#create'
  devise_for :users, :controllers => {:registrations => 'registrations'}
  resources :projects
  resources :tasks
  resources :authentications
  root :to => "projects#home"
  get "sendQuestion/:id" => "projects#send_question", :as => "sendQuestion"
  get "updateQuestionHistory/:project_id/:task_id" => "histories#updateQuestionHistory", :as => "updateQuestionHistory"
  get "uqh/:project_id/:task_id" => "histories#updateQuestionHistory", :as => "uqh"
end

app/models/history.rb
class History < ActiveRecord::Base
  belongs_to :project
  belongs_to :task
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  # GET /histories
  # GET /histories.xml
  def index
    @histories = History.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @histories }
    end
  end

  # GET /histories/1
  # GET /histories/1.xml
  def show
    @history = History.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @history }
    end
  end

  # GET /histories/new
  # GET /histories/new.xml
  def new
    @history = History.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @history }
    end
  end

  # GET /histories/1/edit
  def edit
    @history = History.find(params[:id])
  end

  # POST /histories
  # POST /histories.xml
  def create
    @history = History.new(params[:history])

    respond_to do |format|
      if @history.save
        format.html { redirect_to(@history, :notice => 'History was successfully created.') }
        format.xml  { render :xml => @history, :status => :created, :location => @history }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @history.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /histories/1
  # PUT /histories/1.xml
  def update
    @history = History.find(params[:id])

    respond_to do |format|
      if @history.update_attributes(params[:history])
        format.html { redirect_to(@history, :notice => 'History was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @history.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /histories/1
  # DELETE /histories/1.xml
  def destroy
    @history = History.find(params[:id])
    @history.destroy

    respond_to do |format|
      format.html { redirect_to(histories_url) }
      format.xml  { head :ok }
    end
  end
  
  def updateQuestionHistory
    @project = Project.find(params[:project_id])
    @history = History.new(:project_id => params[:project_id], :task_id => params[:task_id])
    if @project.updated_at < Time.now-30.seconds
    	    puts "in"
     @history.save
    end
    
    redirect_to(@project)
  end
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/views/histories/_form.html.erb
<%= form_for(@history) do |f| %>
  <% if @history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@history.errors.count, "error") %> prohibited this history from being saved:</h2>

      <ul>
      <% @history.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :project_id %><br />
    <%= f.text_field :project_id %>
  </div>
  <div class="field">
    <%= f.label :task_id %><br />
    <%= f.text_field :task_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/histories/edit.html.erb
<h1>Editing history</h1>

<%= render 'form' %>

<%= link_to 'Show', @history %> |
<%= link_to 'Back', histories_path %>

app/views/histories/index.html.erb
<h1>Listing histories</h1>

<table>
  <tr>
    <th>Project</th>
    <th>Task</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @histories.each do |history| %>
  <tr>
    <td><%= history.project_id %></td>
    <td><%= history.task_id %></td>
    <td><%= link_to 'Show', history %></td>
    <td><%= link_to 'Edit', edit_history_path(history) %></td>
    <td><%= link_to 'Destroy', history, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New History', new_history_path %>

app/views/histories/new.html.erb
<h1>New history</h1>

<%= render 'form' %>

<%= link_to 'Back', histories_path %>

app/views/histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Project:</b>
  <%= @history.project_id %>
</p>

<p>
  <b>Task:</b>
  <%= @history.task_id %>
</p>


<%= link_to 'Edit', edit_history_path(@history) %> |
<%= link_to 'Back', histories_path %>

app/views/histories/updateQuestionHistory.html.erb
QuestionHistoryUpdated!