config/routes.rb
Todo::Application.routes.draw do
  resources :histories

  match '/auth/:provider/callback' => 'authentications#create'
  devise_for :users, :controllers => {:registrations => 'registrations'}
  resources :projects
  resources :tasks
  resources :authentications
  root :to => "projects#home"
  get "sendQuestion/:id" => "projects#send_question", :as => "sendQuestion"
  get "updateQuestionHistory/:project_id/:task_id" => "histories#updateQuestionHistory", :as => "updateQuestionHistory"
  get "uqh/:project_id/:task_id" => "histories#updateQuestionHistory", :as => "uqh"
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name, :user_id
  belongs_to :user
  has_many :tasks
  has_many :histories
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  require "rubygems"
  require "twitter"

  def home
    @projects = Project.find(:all, :order => 'created_at desc')  
  end
  
  def index
    @projects = current_user.projects.all
  end
  
  def show
    @project = Project.find(params[:id])
    @histories = @project.histories.find(:all, :select => 'count(*) count, task_id', :group => 'task_id')
  end
  
  def new
    @project = current_user.projects.new
  end
  
  def create
   @project = current_user.projects.new(params[:project])
    
    if @project.save
      flash[:notice] = "Successfully created project."
      redirect_to @project
    else
      render :action => 'new'
    end
  end
  
  def edit
    @project = current_user.projects.find(params[:id])
  end
  
  def update
    @project = current_user.projects.find(params[:id])
    if @project.update_attributes(params[:project])
      flash[:notice] = "Successfully updated project."
      redirect_to @project
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @project = current_user.projects.find(params[:id])
    @project.destroy
    flash[:notice] = "Successfully destroyed project."
    redirect_to projects_url
  end
  
  def send_question
    @project = current_user.projects.find(params[:id])
    if @project
        @tasks = @project.tasks.find(:all) 
        use_twitter = current_user.authentications.find_by_provider('twitter')
        use_facebook = current_user.authentications.find_by_provider('facebook')
        
    	sent_to = '' 
    	
        if use_twitter
          sent_to = 'Twitter'	
    	  tweet = Array.new
    	  tweet.push @project.name
    	
    	  @tasks.each do |t|
    	    tweet.push ' ' + t.name + ' ' + 'http://qq.benerino.com/uqh/' + t.project_id.to_s + '/' + t.id.to_s
 	  end
 	 
 	  tweet.each do |st|
    	    current_user.twitter.update(st)   
   	  end
  	end
  	
        if use_facebook
          sent_to += ' & ' if sent_to != ''	
          sent_to += 'Facebook'	
    	  
    	  face = @project.name
    	
    	  @tasks.each do |t|
    	    face += ' -- ' + t.name + ': ' + 'http://qq.benerino.com/uqh/' + t.project_id.to_s + '/' + t.id.to_s
 	  end
 	 
 	  current_user.facebook.feed!(:message => face, :name => @project.name)
  	end
    end
    
    if sent_to != ''
      flash[:notice] = "Question sent to: " + sent_to
    else
      flash[:notice] = "Question did not send. Are you signed in with twitter or facebook?"
    end	    
    redirect_to @project
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  <%= f.error_messages %>
  <%= f.hidden_field :user_id %>
  <p>
    <%= f.label 'Question' %><br />
    <%= f.text_field :name, :id => 'question_input' %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/projects/_list_questions.html.erb
<h1>Questions</h1>

<table>
  <% for project in @projects %>
    <tr>
      <td><%= link_to project.name, project %></td>
      <% if current_user && project.user_id == current_user.id %>
        <td><%= link_to "Edit", edit_project_path(project) %></td>
        <td><%= link_to "Delete", project, :confirm => 'Are you sure?', :method => :delete %></td>
      <% end %>
    </tr>
  <% end %>
</table>

<% if user_signed_in? %>
  <p><%= link_to "New Question", new_project_path %></p>
<% end %>

app/views/projects/edit.html.erb
<% title "Edit Question" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @project %> |
  <%= link_to "View All", projects_path %>
</p>

app/views/projects/home.html.erb
<%= render 'list_questions' %>

app/views/projects/index.html.erb
<% title "Projects" %>

<table>
  <tr>
    <th>Name</th>
  </tr>
  <% for project in @projects %>
    <tr>
      <td><%= link_to project.name, project %></td>
      <td><%= link_to "Edit", edit_project_path(project) %></td>
      <td><%= link_to "Destroy", project, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Project", new_project_path %></p>

app/views/projects/new.html.erb
<% title "New Question" %>

<%= render 'form' %>

<p><%= link_to "Back to List", projects_path %></p>

app/views/projects/send_question.html.erb
Thanks!

app/views/projects/show.html.erb
<%= hidden_field_tag 'question_name', @project.name %>

<h2><%= @project.name %> Answers</h2>
  <% if !current_user || current_user.id != @project.user_id %>
    VOTE by clicking your answer!<br />
  <% end %>
<ul>
  
  <% for task in @project.tasks %>
    <li>
    <% if !current_user || current_user.id != @project.user_id %>
    <%= link_to task.name, updateQuestionHistory_path(:project_id => @project.id, :task_id => task.id) %>
    <% else %>
      <%= task.name %>
    <% end %>
      <% if current_user && @project.user_id == current_user.id %>
      (<%= link_to "Edit", edit_task_path(task) %> |
      <%= link_to "Destroy", task, :confirm => "Are you sure?", :method => :delete %>)
      <% end %>
    </li>
  <% end %>
</ul>


<% if current_user && @project.user_id == current_user.id %>
<p>
  <%= link_to "New Answer", new_task_path(:project_id => @project) %> |
  <%= link_to "Send Question", sendQuestion_path(:id => @project) %>
</p>
<% end %>

<% if !@histories.empty? %>

<%= hidden_field_tag 'histories_array', make_array(@histories) %>
<div id="user_graph"></div>

<% else %>
 No Replies yet! Relax
<% end %>